import { generateOpenAiImageObjectQuery } from '@/platforms/ai';
import {
  AiAutoGeneratedField,
  getAiImageQuerySchema,
  getAiTextFieldsToGenerate,
} from '.';
import { AI_TEXT_AUTO_GENERATED_FIELDS } from '@/app/config';
import { PhotoFormData } from '../form';
import { Tags } from '@/tag';

export const generateAiImageQueries = async ({
  imageBase64,
  textFieldsToGenerate = [],
  existingTitle,
  uniqueTags,
  isBatch,
}: {
  imageBase64?: string
  textFieldsToGenerate: AiAutoGeneratedField[]
  existingTitle?: string
  uniqueTags: Tags
  isBatch?: boolean
}): Promise<{
  title?: string
  caption?: string
  tags?: string
  semantic?: string
  // FORK: bilingual (Simplified-Chinese) siblings; tags as CSV like `tags`.
  titleZh?: string
  captionZh?: string
  tagsZh?: string
  semanticZh?: string
  error?: string
}> => {
  if (imageBase64) {
    try {
      const { query, schema } = getAiImageQuerySchema(
        textFieldsToGenerate,
        existingTitle,
        uniqueTags,
      );
      // The object query returns tags as normalized string[] (PLOG-9); re-join
      // to the CSV string callers expect. zh siblings mirror their en field.
      const r = await generateOpenAiImageObjectQuery(
        imageBase64,
        query,
        schema,
        isBatch,
      ) as {
        title?: string
        caption?: string
        tags?: string[]
        semantic?: string
        title_zh?: string | null
        caption_zh?: string | null
        tags_zh?: string[] | null
        semantic_zh?: string | null
      };
      return {
        ...(r.title && { title: r.title }),
        ...(r.caption && { caption: r.caption }),
        ...(r.tags && { tags: r.tags.join(', ') }),
        ...(r.semantic && { semantic: r.semantic }),
        ...(r.title_zh && { titleZh: r.title_zh }),
        ...(r.caption_zh && { captionZh: r.caption_zh }),
        ...(r.tags_zh && { tagsZh: r.tags_zh.join(', ') }),
        ...(r.semantic_zh && { semanticZh: r.semantic_zh }),
      };
    } catch (e: any) {
      return {
        error: e.message,
      };
    }
  } else {
    return {
      error: 'No image provided',
    };
  }
};

export const addAiTextToFormData = async ({
  formData = {},
  imageBase64,
  existingTitle,
  existingTags,
  uniqueTags,
}: {
  formData?: Partial<PhotoFormData>
  imageBase64?: string
  existingTitle?: string
  existingTags?: string
  uniqueTags: Tags
}): Promise<Partial<PhotoFormData>> => {
  const {
    title: aiTitle,
    caption: aiCaption,
    tags: aiTags,
    semantic,
    titleZh,
    captionZh,
    tagsZh,
    semanticZh,
  } = await generateAiImageQueries({
    imageBase64,
    textFieldsToGenerate: getAiTextFieldsToGenerate(
      AI_TEXT_AUTO_GENERATED_FIELDS,
      Boolean(existingTitle || formData?.title),
      Boolean(formData?.caption),
      Boolean(existingTags || formData?.tags),
    ),
    existingTitle: existingTitle || formData?.title,
    uniqueTags,
  });

  return {
    ...formData,
    title: formData?.title || aiTitle,
    caption: formData?.caption || aiCaption,
    tags: formData?.tags || aiTags,
    semanticDescription: semantic,
    // FORK: bilingual siblings (no existing-value guard — these are new fields).
    titleZh,
    captionZh,
    tagsZh,
    semanticDescriptionZh: semanticZh,
  };
};
