import { useCallback, useEffect, useRef } from 'react';
import useAiImageQuery from './useAiImageQuery';
import useAiImageTagsQuery from './useAiImageTagsQuery';
import useTitleCaptionAiImageQuery from './useTitleCaptionAiImageQuery';
import { AI_AUTO_GENERATED_FIELDS_ALL, AiAutoGeneratedField } from '.';

export type AiContent = ReturnType<typeof useAiImageQueries>;

export default function useAiImageQueries(
  // Direct thumbnail base64 (upload — image is already in memory).
  imageBase64?: string,
  // Lazy resolver (edit — fetch the thumbnail on first AI request). PLOG-5.
  getImageBase64Lazy?: () => Promise<string | undefined>,
  textFieldsToAutoGenerate: AiAutoGeneratedField[] = [],
) {
  // Resolve the thumbnail ONCE per session, shared across all 5 sub-queries.
  // Cache the in-flight promise (not the value) so a "generate all" click that
  // fires several requests concurrently triggers a single lazy fetch.
  const lazyPromiseRef = useRef<Promise<string | undefined>>(undefined);
  const resolveImageBase64 = useCallback(async () => {
    if (imageBase64) { return imageBase64; }
    if (getImageBase64Lazy) {
      if (!lazyPromiseRef.current) {
        // Cache the in-flight promise to dedupe concurrent requests, but DON'T
        // cache a failed/empty resolution — clear the ref so a retry re-fetches
        // (a transient failure must not permanently disable AI generation).
        lazyPromiseRef.current = getImageBase64Lazy()
          .then(value => {
            if (!value) { lazyPromiseRef.current = undefined; }
            return value;
          })
          .catch(e => {
            lazyPromiseRef.current = undefined;
            throw e;
          });
      }
      return lazyPromiseRef.current;
    }
    return imageBase64;
  }, [imageBase64, getImageBase64Lazy]);

  const [
    requestTitleCaption,
    _title,
    _caption,
    _isLoadingTitle,
    _isLoadingCaption,
    resetTitle,
    resetCaption,
  ] = useTitleCaptionAiImageQuery(resolveImageBase64);

  const [
    requestTitle,
    titleSolo,
    isLoadingTitleSolo,
    resetTitleSolo,
  ] = useAiImageQuery(resolveImageBase64, 'title');

  const [
    requestCaption,
    captionSolo,
    isLoadingCaptionSolo,
    resetCaptionSolo,
  ] = useAiImageQuery(resolveImageBase64, 'caption');

  // PLOG-15: tags via the NON-streaming object path (faceted + bilingual),
  // matching the batch/backfill generator. Returns tags AND tagsZh.
  const [
    requestTags,
    tags,
    tagsZh,
    isLoadingTags,
  ] = useAiImageTagsQuery(resolveImageBase64);

  const [
    requestSemantic,
    semanticDescription,
    isLoadingSemantic,
  ] = useAiImageQuery(resolveImageBase64, 'semantic');

  const title = _title || titleSolo;
  const caption = _caption || captionSolo;
  const isLoadingTitle = _isLoadingTitle || isLoadingTitleSolo;
  const isLoadingCaption = _isLoadingCaption || isLoadingCaptionSolo;

  const isLoading =
    isLoadingTitle ||
    isLoadingCaption ||
    isLoadingTags ||
    isLoadingSemantic;

  const hasRunAllQueriesOnce = useRef(false);

  const request = useCallback(async (
    fields = AI_AUTO_GENERATED_FIELDS_ALL,
  ) => {
    if (process.env.NODE_ENV !== 'production') {
      console.log('RUNNING AI QUERIES', fields);
    }
    hasRunAllQueriesOnce.current = true;
    if (fields.includes('title') && fields.includes('caption')) {
      // Unmask individual title + caption
      resetTitleSolo();
      resetCaptionSolo();
      requestTitleCaption();
    } else {
      if (fields.includes('title')) {
        // Unmask combined title
        resetTitle();
        resetTitleSolo();
        requestTitle();
      }
      if (fields.includes('caption')) {
        // Unmask combined caption
        resetCaption();
        resetCaptionSolo();
        requestCaption();
      }
    }
    if (fields.includes('tags')) { requestTags(); }
    if (fields.includes('semantic')) { requestSemantic(); }
  }, [
    requestTitleCaption,
    requestTitle,
    requestCaption,
    requestTags,
    requestSemantic,
    resetTitle,
    resetTitleSolo,
    resetCaption,
    resetCaptionSolo,
  ]);

  useEffect(() => {
    if (imageBase64 && !hasRunAllQueriesOnce.current) {
      if (textFieldsToAutoGenerate.length > 0) {
        request(textFieldsToAutoGenerate);
      }
    }
  }, [textFieldsToAutoGenerate, imageBase64, request]);

  return {
    request,
    title,
    caption,
    tags,
    tagsZh,
    semanticDescription,
    isLoading,
    isLoadingTitle,
    isLoadingCaption,
    isLoadingTags,
    isLoadingSemantic,
  };
}
